---
- name: Set up web server
  hosts: all
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - nginx
    - letsencrypt

- name: Set up CONSUL
  hosts: all
  become: true
  vars:
    # https://github.com/ansible/proposals/issues/89
    ansible_user: "{{ deploy_user }}"
  roles:
    - ruby
    - folder_structure
    - rails
    - email
    - queue
    - puma

- name: Post-installation tasks
  hosts: all
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - memcached
    - timezone

- name: Check system
  hosts: all
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - specs
