---
- name: Create deploy user
  hosts: all
  become: yes
  roles:
    - user

- name: Set up system
  hosts: all
  roles:
    - system
    - postgresql

- name: Set up CONSUL
  hosts: all
  become: true
  become_user: "{{ deploy_user }}"
  roles:
    - ruby
    - rails
    - ssl
    - email
    - queue
    - unicorn
    - nginx
    - memcached
    - timezone
    # - capistrano
